---
- name: Configuring apache using multiple child playbooks
  hosts: all
  tasks:
    - name: Call childplaybooks for apache
      include: "{{item}}"
      with_items:
        - install.yml
        - edit_index.yml
        - restart.yml
        - check_url_response.yml
