---
- name: Configure apache2/httpd on all servers
  hosts: all
  tasks:
    - name: Install apache2 on Ubuntu servers
      apt:
        name: apache2
        state: present
        update_cache: yes
      when: ansible_distribution == "Ubuntu"
    - name: Install httpd on Redhat servers
      yum:
        name: httpd
        state: present
        update_cache: yes
      when: ansible_distribution == "RedHat"
    - name: Edit the index.html file
      copy:
        content: "IntelliQIt"
        dest: /var/www/html/index.html
    - name: Restart apache2 on Ubtuntu servers
      service:
        name: apache2
        state: restarted
      when: ansible_distribution == "Ubuntu"
    - name: Restart httpd on Redhat servers
      service:
        name: httpd
        state: restarted
      when: ansible_distribution == "RedHat"
    - name: Check apache/httpd response
      uri:
        url: "{{item}}"
        status_code: 200
      with_items:
        - http://172.31.0.35
        - http://172.31.18.136
        - http://172.31.31.222
...






