---
- name: Create user using host scope variables
  hosts: 172.31.18.136
  tasks:
    - name: Create user
      user:
        name: "{{a}}"
        password: "{{b}}"
        home: "{{c}}"
        uid: "{{d}}"
        shell: "{{e}}"
        comment: "{{f}}"
...

