---
- name: Capture Os info of all servers
  hosts: all
  tasks:
    - name: Capture OS name
      debug:
        msg: "{{ansible_distribution}}"
    - name: Capture OS version
      debug:
        msg: "{{ansible_distribution_version}}"
    - name: Capture OS major version
      debug:
        msg: "{{ansible_distribution_major_version}}"
