---
- name: Error Handling
  hosts: all
  tasks:
    - block:
       - name: Install git using apt on Ubuntu servers
         apt:
           name: git
           state: present
           update_cache: yes
      rescue:
        - name: Install git using yum on Redhat servers
          yum:
            name: git
            state: present
            update_cache: yes
      always:
        - name: Display success msg
          debug:
            msg: "Git installtion successfull"
